name: Benchmarks

on:
  pull_request:
    branches: [main]

permissions:
  pull-requests: write

jobs:
  benchmark:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: feat/benchmarks

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
      
      - name: Benchmark main (baseline)
        run: cargo bench -p raptor --features internal --bench raptor -- --save-baseline main

      - uses: actions/checkout@v4
        with:
          clean: false

      - name: Benchmark PR vs main
        run: cargo bench -p raptor --features internal --bench raptor -- --format terse --baseline-lenient main | tee bench-output.txt

      - name: Post benchmark comment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BODY="## Benchmark results

          \`\`\`
          $(cat bench-output.txt)
          \`\`\`"

          # either edit the last comment, if doesn't exist, create a new comment
          gh pr comment ${{ github.event.number }} --body "$BODY" --edit-last || \
          gh pr comment ${{ github.event.number }} --body "$BODY"
